name: "fleepness"

services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailpit
            - selenium
            - minio
            - soketi
    authserver:
        image: quay.io/keycloak/keycloak:23.0.5
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - mysql
        networks:
            - sail
        # ports:
        #     - 8082:8080
        environment:
            # - KC_DB=mysql
            # - KC_DB_URL_PORT=3306
            # - KC_DB_URL_DATABASE=fleepness_auth
            # - KC_DB_USERNAME='${DB_USERNAME}'
            # - KC_DB_PASSWORD='${DB_PASSWORD}'
            - KEYCLOAK_ADMIN=fleepness
            - KEYCLOAK_ADMIN_PASSWORD=Fleepness12345#
        command: start-dev
    mysql:
        image: 'mysql/mysql-server:8.0'
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        # ports:
        #     - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: seleniarm/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
    imgproxy:
        image: darthsim/imgproxy
        environment:
            IMGPROXY_KEY: "${IMGPROXY_KEY}"
            IMGPROXY_SALT: "${IMGPROXY_SALT}"
            # IMGPROXY_SIGNATURE_SIZE: 32
            IMGPROXY_USE_S3: "true"
            IMGPROXY_S3_ENDPOINT: "http://minio:9000"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            IMGPROXY_SECRET: "${IMGPROXY_SECRET}"
            IMGPROXY_ENABLE_DEBUG_HEADERS: true
            # IMGPROXY_ALLOW_ORIGIN: ""
            # IMGPROXY_ALLOWED_SOURCES: "https://*.fleepness.com/"
        ports:
            - 8080:8080
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "imgproxy", "health" ]
            timeout: "10s"
            interval: "10s"
            retries: 3
    minio:
        image: 'minio/minio:latest'
        # ports:
        #     - '${FORWARD_MINIO_PORT:-9000}:9000'
        #     - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: sail
            MINIO_ROOT_PASSWORD: password
            MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK: "http://authserver:8080/realms/fleepness-s3/.well-known/openid-configuration"
            MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK: "minio"
            MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK: uwTjlJvCVodeZ2HnkS1nXxQ9rBbzE92U
            MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK: "Fleepness S3 OpenID"
            MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK: "openid"
            MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK: "on"

            MINIO_IDENTITY_OPENID_VENDOR_KEYCLOAK: "keycloak"
            MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL_KEYCLOAK: "http://authserver:8080/admin"
            MINIO_IDENTITY_OPENID_KEYCLOAK_REALM_KEYCLOAK: "fleepness-s3"
            MINIO_IDENTITY_OPENID_CLAIM_NAME_KEYCLOAK: "policy"
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - sail
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - sail
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8082:80
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
            - "mysql:db"
        depends_on:
            - mysql
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-minio:
        driver: local
