name: fleepness

services:
  backend:
    build:
      context: .
      dockerfile: ./runtimes/8.2/Dockerfile
      args:
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
        SCHEDULED_NOTIFICATION_PRUNE_AGE: 7
        PHP_OPCACHE_MAX_ACCELERATED_FILES: "10000"
        PHP_OPCACHE_MEMORY_CONSUMPTION: "192"
        PHP_OPCACHE_MAX_WASTED_PERCENTAGE: "10"
    environment:
      APP_NAME: "${FLEEPNESS_APP_NAME}"
      MEDIA_DISK: "${FLEEPNESS_MEDIA_DISK}"
      ASSET_URL: "${FLEEPNESS_ASSET_URL}"
      APP_ENV: "${FLEEPNESS_APP_ENV}"
      APP_KEY: "${FLEEPNESS_APP_KEY}"
      APP_DEBUG: "${FLEEPNESS_APP_DEBUG}"
      APP_URL: "${FLEEPNESS_APP_URL}"
      SPA_RESET_PASSWORD_BASE_URL: "${FLEEPNESS_SPA_RESET_PASSWORD_BASE_URL}"
      LOG_CHANNEL: "${FLEEPNESS_LOG_CHANNEL}"
      LOG_DEPRECATIONS_CHANNEL: "${FLEEPNESS_LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${FLEEPNESS_LOG_LEVEL}"
      DB_CONNECTION: "${FLEEPNESS_DB_CONNECTION}"
      DB_HOST: "${FLEEPNESS_DB_HOST}"
      DB_PORT: "${FLEEPNESS_DB_PORT}"
      DB_DATABASE: "${FLEEPNESS_DB_DATABASE}"
      DB_USERNAME: "${FLEEPNESS_DB_USERNAME}"
      DB_PASSWORD: "${FLEEPNESS_DB_PASSWORD}"
      BROADCAST_DRIVER: "${FLEEPNESS_BROADCAST_DRIVER}"
      CACHE_DRIVER: "${FLEEPNESS_CACHE_DRIVER}"
      QUEUE_CONNECTION: "${FLEEPNESS_QUEUE_CONNECTION}"
      SESSION_DRIVER: "${FLEEPNESS_SESSION_DRIVER}"
      SESSION_LIFETIME: "${FLEEPNESS_SESSION_LIFETIME}"
      REDIS_HOST: "${FLEEPNESS_REDIS_HOST}"
      REDIS_PASSWORD: "${FLEEPNESS_REDIS_PASSWORD}"
      REDIS_PORT: "${FLEEPNESS_REDIS_PORT}"
      MAIL_DRIVER: "${FLEEPNESS_MAIL_DRIVER}"
      MAIL_HOST: "${FLEEPNESS_MAIL_HOST}"
      MAIL_PORT: "${FLEEPNESS_MAIL_PORT}"
      MAIL_USERNAME: "${FLEEPNESS_MAIL_USERNAME}"
      MAIL_PASSWORD: "${FLEEPNESS_MAIL_PASSWORD}"
      MAIL_FROM_ADDRESS: "${FLEEPNESS_MAIL_FROM_ADDRESS}"
      MAIL_ENCRYPTION: "${FLEEPNESS_MAIL_ENCRYPTION}"
      MAIL_FROM_NAME: "${FLEEPNESS_MAIL_FROM_NAME}"
      FILESYSTEM_DISK: "${FLEEPNESS_FILESYSTEM_DISK}"
      AWS_ACCESS_KEY_ID: "${FLEEPNESS_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${FLEEPNESS_AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${FLEEPNESS_AWS_DEFAULT_REGION}"
      AWS_BUCKET: "${FLEEPNESS_AWS_BUCKET}"
      AWS_ENDPOINT: "${FLEEPNESS_AWS_ENDPOINT}"
      AWS_USE_PATH_STYLE_ENDPOINT: "${FLEEPNESS_AWS_USE_PATH_STYLE_ENDPOINT}"
      AWS_URL: "${FLEEPNESS_AWS_URL}"
      SCOUT_DRIVER: "${FLEEPNESS_SCOUT_DRIVER}"
      MEILISEARCH_HOST: "${FLEEPNESS_MEILISEARCH_HOST}"
      MEILISEARCH_NO_ANALYTICS: "${FLEEPNESS_MEILISEARCH_NO_ANALYTICS}"
      SPA_EMAIL_VERIFICATION_BASE_URL: "${FLEEPNESS_SPA_EMAIL_VERIFICATION_BASE_URL}"
      PUSHER_APP_ID: "${FLEEPNESS_PUSHER_APP_ID}"
      PUSHER_APP_KEY: "${FLEEPNESS_PUSHER_APP_KEY}"
      PUSHER_APP_SECRET: "${FLEEPNESS_PUSHER_APP_SECRET}"
      PUSHER_HOST: "${FLEEPNESS_PUSHER_HOST}"
      PUSHER_PORT: "${FLEEPNESS_PUSHER_PORT}"
      PUSHER_SCHEME: "${FLEEPNESS_PUSHER_SCHEME}"
      PUSHER_APP_CLUSTER: "${FLEEPNESS_PUSHER_APP_CLUSTER}"
      IMGPROXY_KEY: "${FLEEPNESS_IMGPROXY_KEY}"
      IMGPROXY_SALT: "${FLEEPNESS_IMGPROXY_SALT}"
      IMGPROXY_SECRET: "${FLEEPNESS_IMGPROXY_SECRET}"
      IMGPROXY_URL: "${FLEEPNESS_IMGPROXY_URL}"
      AUTHORIZATION_SERVER_URL: "${FLEEPNESS_AUTHORIZATION_SERVER_URL}"
      AUTHORIZATION_SERVER_CLIENT_ID: "${FLEEPNESS_AUTHORIZATION_SERVER_CLIENT_ID}"
      AUTHORIZATION_SERVER_CLIENT_SECRET: "${FLEEPNESS_AUTHORIZATION_SERVER_CLIENT_SECRET}"
      AUTHORIZATION_SERVER_TOKEN_URL: "${FLEEPNESS_AUTHORIZATION_SERVER_TOKEN_URL}"
      AUTHORIZATION_SERVER_INTROSPECT_URL: "${FLEEPNESS_AUTHORIZATION_SERVER_INTROSPECT_URL}"
      LIVEKIT_HOST: "${FLEEPNESS_LIVEKIT_HOST}"
      LIVEKIT_API_KEY: "${FLEEPNESS_LIVEKIT_API_KEY}"
      LIVEKIT_API_SECRET: "${FLEEPNESS_LIVEKIT_API_SECRET}"
      FIREBASE_CREDENTIALS: "${FLEEPNESS_FIREBASE_CREDENTIALS}"
      SSLCZ_STORE_ID: "${FLEEPNESS_SSLCZ_STORE_ID}"
      SSLCZ_STORE_PASSWORD: "${FLEEPNESS_SSLCZ_STORE_PASSWORD}"
      SSLCZ_TESTMODE: "${FLEEPNESS_SSLCZ_TESTMODE}"
      SSLCZ_SUCCESS_URL: "${FLEEPNESS_SSLCZ_SUCCESS_URL}"
      SSLCZ_FAIL_URL: "${FLEEPNESS_SSLCZ_FAIL_URL}"
      SSLCZ_CANCEL_URL: "${FLEEPNESS_SSLCZ_CANCEL_URL}"
      SSLCZ_IPN_URL: "${FLEEPNESS_SSLCZ_IPN_URL}"
      PATHAO_API_BASE: "${FLEEPNESS_PATHAO_API_BASE}"
      PATHAO_CLIENT_ID: "${FLEEPNESS_PATHAO_CLIENT_ID}"
      PATHAO_CLIENT_SECRET: "${FLEEPNESS_PATHAO_CLIENT_SECRET}"
      PATHAO_CLIENT_EMAIL: "${FLEEPNESS_PATHAO_CLIENT_EMAIL}"
      PATHAO_CLIENT_PASSWORD: "${FLEEPNESS_PATHAO_CLIENT_PASSWORD}"
      PATHAO_GRANT_TYPE: "${FLEEPNESS_PATHAO_GRANT_TYPE}"
      PATHAO_WEBHOOK_SECRET: "${FLEEPNESS_PATHAO_WEBHOOK_SECRET}"
    networks:
      - fleepness_webserver
      - fleepness
    depends_on:
      fleepness_mysql:
        condition: service_healthy
        restart: true
      fleepness_redis:
        condition: service_healthy
        restart: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
  fleepness_mysql:
    image: "mysql/mysql-server:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "${FLEEPNESS_DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${FLEEPNESS_DB_DATABASE}"
      MYSQL_USER: "${FLEEPNESS_DB_USERNAME}"
      MYSQL_PASSWORD: "${FLEEPNESS_DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "fleepness-mysql:/var/lib/mysql"
    restart: always
    networks:
      - fleepness
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${FLEEPNESS_DB_PASSWORD}"
      retries: 3
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 256m
  fleepness_redis:
    restart: always
    image: "redis:alpine"
    volumes:
      - "fleepness-redis:/data"
    networks:
      - fleepness
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 256m
networks:
  fleepness:
    driver: bridge
  fleepness_webserver:
    external: true
volumes:
  fleepness-mysql:
    driver: local
  fleepness-redis:
    driver: local
